Capstone Project
DanUshindi/Capston-first-module pull request #1
Opened 2022-03-10 16:01 UTC by DanUshindi

In this project I have to :
- personalize the content of your page. Choose a topic that is different than the one in the original design.
- You should build only these 2 pages:

     The home page.
     The about page.
- Each of these pages should have versions for 2 different screen sizes:

      Mobile: up to 768px wide.
       Desktop: 768px or wider.
- Interactions

    Links
   The home page should have a link in the menu to the about page.
   The logo in the header links to the home page.
   Mobile menu
   When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
  There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design 
  (colors, typography, spacings, etc.).
  The mobile menu should have a close (X) button that closes the menu.
  Dynamic page

- The section "Featured speakers" should be created dynamically in JavaScript.
You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

2022-03-10 23:40 UTC, Gambit142 requested changes
Hi @DanUshindi 👍, 

Good job so far!

### Highlights
- Linters checks passed ✔️ 
- I like the way you implemented the show more and less for the main guests' section. 👍 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

Apart from the comments below, kindly consider these as required changes also:

- It would be nice for you to retake the video because the current video presentation is not audible and thus, I can't hear the presentation of the project's features.
- For this project, we are to use the following colors according to the template given:
  - `#272A31`
  - `#EC5242`
  - `#D3D3D3 `
- Kindly use the font-family `Cocogoose` for your `<hx>` tags

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider the optional change I suggested.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-10 23:40 UTC, Gambit142 commented on README.md
- [x] The images do not show when I view your project through the live demo link. It would be nice to use push to `gh-Pages` from the current branch.
- [x] When I click the _**About Page,**_ I get a `404 Page not found` error. 
- [x] The Featured Speaker section does not show also.

### 404 Error

![image](https://user-images.githubusercontent.com/77106962/157765524-1183d085-baab-4dfe-ad3d-e4eb12bde843.png)

### Featured Speaker Section and Broken Images

![image](https://user-images.githubusercontent.com/77106962/157766015-355aaed6-3723-471b-99da-af89c9692812.png)

2022-03-10 23:40 UTC, Gambit142 commented on README.md
> +
- [x] (Optional) Kindly take a proper screenshot of the project if you want to include a screenshot in your `README.md` file. If you do not need it, you can remove it.

2022-03-10 23:40 UTC, Gambit142 commented on README.md
- [x] In your acknowledgement section, kindly give credit to Cindy Shin of Behance. In the professional world, it is appropriate to give credit to people if their intellectual property was used to complete your project.

2022-03-10 23:40 UTC, Gambit142 commented on index.js
> +}
- [x] On the mobile view of the _**About Page**_, when  I click the `Hamburger` button, it doesn't display the mobile menu. Kindly fix the bug 👍

2022-03-10 23:40 UTC, Gambit142 commented on style.css
> +}
- [x] Kindly make the `background-color` of the mobile menu transparent. This way you would be fulfilling a major project requirement. 👍

2022-03-10 23:40 UTC, Gambit142 commented on partners.html
> +        </div>
- [x] For the mobile view of both the **Home** and **About** Page, the footer should have a white background. Remember that your design should follow the template given for this project. It would be nice to implement it.

2022-03-10 23:40 UTC, Gambit142 commented on index.html
> +  </section>
- [ ] It would be nice to make your design look like that of the Behance template given for this project. Kindly design the top section to look like that of Behance. 🙇 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/157768209-b15b5e1a-3cbe-4ed8-9034-52bd3cefef19.png)

### Behance Design

![image](https://user-images.githubusercontent.com/77106962/157768286-3afa7d7c-7a70-4944-a25b-47c251178671.png)

2022-03-10 23:40 UTC, Gambit142 commented on data.js
> +}, {
- [x] Kindly note that for this section, an `image` should be stored in each object of the array. By implication, you should use actual `images` and not `background-images` for this section. Images are used in a project when it is part of the core feature of the design while background images are used to beautify a web page. Kindly implement this 👍 
- [x] Kindly make the images for this section look like that of the images used in the design template.

### Your Design

![image](https://user-images.githubusercontent.com/77106962/157769220-85813e14-d552-4640-a47b-7d6301c8b9b7.png)

### Behance Design

![image](https://user-images.githubusercontent.com/77106962/157769438-0cd0a079-42e7-4d4b-a5eb-c5516c569b85.png)

2022-03-10 23:40 UTC, Gambit142 commented on partners.html
> +    </section>
- [ ] The text for this section should be aligned to the center and not the left side. Kindly implement this. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/157769720-6b50cc26-bf85-4f7e-8595-0834ccfa44ba.png)

### Behance Design

![image](https://user-images.githubusercontent.com/77106962/157769908-f92acf67-8690-4e6b-a8cb-b613be70779b.png)

2022-03-10 23:40 UTC, Gambit142 commented on partners.html
> +    </section>
I would like to point out some design details for this section:

- [ ] Kindly use `images` and not `background-images` for this section, if an image is a core feature of a project, it is suggested that an `<img>` tag be used but if it is to design the page, `background-image` should be used. 👍 
- [ ] On mobile, the images should be vertically arranged while on desktop, they should be horizontally arranged. 

### Behance Design (Mobile)

![image](https://user-images.githubusercontent.com/77106962/157770890-df46946f-23e4-45b9-a48c-785161e77bf1.png)

### Behance Design (Desktop)

![image](https://user-images.githubusercontent.com/77106962/157770978-7ec1245a-9414-41db-bfb3-46eb8435e979.png)

2022-03-10 23:40 UTC, Gambit142 commented on partners.html
> +          <li class="nav-item"><a href="/partners.html">About</a></li>
- [ ] The _**About Page**_ should have a link that directs visitors of this app to the main page. Kindly change this to the link to the `Home Page`. 👍

2022-03-10 23:40 UTC, Gambit142 commented on partners.html
> +    <div class="first-section-nav">
- [ ] It would be nice to use the `<nav>` tag instead of the `<div>` tag used here for semantic purposes.

2022-03-10 23:40 UTC, Gambit142 commented on index.html
> +    <div class="first-section-nav">
- [ ] It would be nice to use the `<nav>` tag instead of the `<div>` tag used here for semantic purposes.

2022-03-10 23:40 UTC, Gambit142 commented on data.js
> +  <div class= "${project.picture}">
- [ ] It would be nice to wrap a single speaker in an `<article>` tag instead of the `<div>` tag used here for semantic purposes.

2022-03-11 18:49 UTC, Deepakdanger requested changes
Hi @DanUshindi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] As requested by the previous reviewer, Kindly use the same design as in the original website.
- Your Website 
![Screenshot from 2022-03-11 23-34-55](https://user-images.githubusercontent.com/26767383/157932276-f0ee6de1-06e4-49e7-9d3e-1546a7142bce.png)

- Original website ![157769438-0cd0a079-42e7-4d4b-a5eb-c5516c569b85](https://user-images.githubusercontent.com/26767383/157932311-a8f4f2d1-e41c-4905-8b39-e5fb8ab5e1f6.png)

- [ ] As Requested by previous reviewer ,In **MOBILE view** there should be footer with white background in about page. 
![Screenshot from 2022-03-11 22-51-27](https://user-images.githubusercontent.com/26767383/157932617-bb24b6ad-74d9-4205-b6b4-93cc29720f17.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 20:23 UTC, DanUshindi commented
> Hi @DanUshindi,
> 
> Great work on making the changes requested by a previous reviewer clap You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> ## Required Changes 
> * [x]  As requested by the previous reviewer, Kindly use the same design as in the original website.
> * Your Website
>   ![Screenshot from 2022-03-11 23-34-55](https://user-images.githubusercontent.com/26767383/157932276-f0ee6de1-06e4-49e7-9d3e-1546a7142bce.png)
> * Original website ![157769438-0cd0a079-42e7-4d4b-a5eb-c5516c569b85](https://user-images.githubusercontent.com/26767383/157932311-a8f4f2d1-e41c-4905-8b39-e5fb8ab5e1f6.png)
> * [x]  As Requested by previous reviewer ,In **MOBILE view** there should be footer with white background in about page.
>   ![Screenshot from 2022-03-11 22-51-27](https://user-images.githubusercontent.com/26767383/157932617-bb24b6ad-74d9-4205-b6b4-93cc29720f17.png)
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> * N/A
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Here are the changes implemented, keep in mind that details of the technical implementation are not the requirements, there are countless ways these features can be implemented and this is one of them.
- The speakers' images now have the other checkered square behind them and I think that's the goal
![screencapture-127-0-0-1-5500-index-html-2022-03-11-22_02_01 (1) (1)](https://user-images.githubusercontent.com/93817508/157954373-f14f2be4-de96-4429-b6e2-a08e38523007.png)
- The two pages now have a footer as requested by a previous reviewer
![screencapture-127-0-0-1-5500-index-html-2022-03-11-22_11_22 (1)](https://user-images.githubusercontent.com/93817508/157954710-e7008eba-4bdb-4c60-969b-d0afb11bcea5.png)


### :warning: Useful links :warning:
- Kindly take the time to check to design template before reviewing the UI
  - [CC Global Summit 2015 by Cindy Shin](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- Kindly check the requirements that were provided to us
  - [Project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md)

2022-03-11 21:27 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @DanUshindi ** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media4.giphy.com/media/kSbIoqZ1dZ3b8xb1vR/giphy.gif"/>

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 21:31 UTC, merged